---
name: WWW-OPG
version: 1.003
author:
  - 'Jonathan Yu <jawnsy@cpan.org>'
abstract: Perl interface to Ontario Power Generation's site
license: unrestricted
build_requires:
  Test::NoWarnings: 0.084
requires:
  DateTime: 0.4305
  LWP::UserAgent: 0
  Test::More: 0.62
  perl: 5.006
configure_requires:
  Module::Build: 0.35
dynamic_config: 0
provides:
  WWW::OPG:
    file: lib/WWW/OPG.pm
    version: 1.003
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
resources:
  Ratings: http://cpanratings.perl.org/d/WWW-OPG
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=WWW-OPG
  license: http://edwardsamuels.com/copyright/beyond/articles/public.html
  repository: http://svn.ali.as/cpan/trunk/WWW-OPG
